### ISSUE TITLE
"Update is available" for latest versions

### ISSUE THREAD

**Issue by hovancik** [Tobi823/ffupdater#11]
Hi,  

app is sending me notifications about new versions.

![ff](https://user-images.githubusercontent.com/4745859/91414147-6d789900-e84c-11ea-8541-97bd184e30ba.jpeg)

I've just installed your app from Fdroid. Have Firefox and Lockbox from Play Store.

**Comment by Tobi823** [comment]
This is a limitation of the Mozilla CI Api which I'm using for Firefox Klar, Firefox Focus, Firefox, "normal" Firefox, Firefox for Android Beta and Firefox Nightly:
FFUpdater can't detect the current installed version of these apps if they are installed or updated externally (e.g. Google Play Store). That's why FFUpdater assumes that you have an outdated version and prompts for an update.

You can:
 - disable the update check for a specific app: click on the gear for settings > Excluded applications
 - or install the update in FFUpdater. Maybe Google Play STore will detect next release that Firefox was already updated by FFUpdater
 - or uninstall Firefox from Google Play Store and install Firefox from FFUpdater. BACKUP YOUR DATA (BOOKMARKS, ...) BECAUSE UNINSTALLING WILL DELETE ALL FIREFOX DATA

I will add this info text to the F-Droid page.

**Comment by hovancik** [comment]
Thanks!
