### ISSUE TITLE
Add Kiwi browser

### ISSUE THREAD

**Issue by CodeCubeNeo** [Tobi823/ffupdater#121]
The title says everything. Kiwi browser is now a fully open source browser that supports a lot of chrome extensions. The repo is here: https://github.com/kiwibrowser/src

**Comment by mmtech2012** [comment]
Upvote.

**Comment by Tobi823** [comment]
Kiwi is now supported by FFUpdater 75.5.0

**Comment by Iey4iej3** [comment]
> Kiwi is now supported by FFUpdater 75.5.0

What was changed since https://github.com/Tobi823/ffupdater/issues/36? Kiwi was open source, if I remember correctly.

**Comment by Tobi823** [comment]
1. I am convinced that redirecting search requests to the servers of the developers has no malicious intent. It seems that it is necessary to get paid by the search engines to finance the development.  https://github.com/kiwibrowser/src#business-model

2. I have added a warning so that you are informed about this behavior (redirecting search requests over the servers of the developer).

**Comment by Tobi823** [comment]
As far as I know Kiwi is still open source (but changed the repository https://github.com/kiwibrowser/src.next)

**Comment by Coool** [comment]
Kiwi Browser has been updated recently to [137.0.7337.0](https://github.com/kiwibrowser/src.next/releases/tag/14310011181) version

Related:
- #621
- #468
- #121
- #36
