### ISSUE TITLE
Add Fennec, bromite, IceCat and Tor browser support

### ISSUE THREAD

**Issue by User1l0** [Tobi823/ffupdater#22]

**Comment by Tobi823** [comment]
**Fennec**: Do you mean the outdated Firefox for Android? Which was replaced by "Firefox Quantum” / Firefox 79? https://blog.mozilla.org/blog/2020/08/25/introducing-a-new-firefox-for-android-experience/ - I don't want to support outdated browsers (because security vulnerabilities)

**Bromite**: Do you mean this: https://github.com/bromite/bromite ? Looks good to me. I can implement it.

**IceCat**: IceCat is already in F-Droid https://f-droid.org/en/packages/org.gnu.icecat/ - why should I support it?

**Tor browser**: I will not support it because it can be installed with F-Droid. Go to Settings > Repositories > Enable "Guardian Project Archive". Then refresh F-Droid by downswiping in Latest and search for "Tor Browser for Android"

**Comment by User1l0** [comment]
Add kiwi browser support it has github release page too github.com/kiwibrowser/android/releases

**Comment by bershanskiy** [comment]
> Add kiwi browser support it has github release page too github.com/kiwibrowser/android/releases

That repository is [archived](https://github.com/kiwibrowser/android), the new one is: https://github.com/kiwibrowser/src
This new repo has never releases ([Nov 4, 2020](https://github.com/kiwibrowser/src/releases/tag/345153190) vs [Oct 7, 2019](https://github.com/kiwibrowser/android/releases/tag/20191007)).

**Comment by Tobi823** [comment]
With the next version (should be 72.1) Bromite will be supported

**Comment by Tobi823** [comment]
With the next version (should be 72.1) Kiwi will also be supported.

Fennec will be not supported, because it's outdated.
Tor Browser will also be not supported, because for some people is the usage of Tor Browser dangerous and they should rely on more experienced app developers (like F-Droid with the "Guardian Project Archive" repository)

**Comment by Tobi823** [comment]
I've removed the Kiwi Browser because it is at least not privacy friendly and in the worst case a spyware Tobi823/ffupdater#35

**Comment by bluecheeser** [comment]
Fennec gets updates fairly now pls add

**Comment by Tobi823** [comment]
I forgot to update my comment here:

> I've removed the Kiwi Browser because it is at least not privacy friendly and in the worst case a spyware #35

There has been a discussion on Github if the Kiwi browser is spyware: https://github.com/Tobi823/ffupdater/issues/35 (Tobi823/ffupdater#35)
   I think that Kiwi is not spyware but stays removed because FFUpdater is about privacy and Kiwi has no additional privacy features.
   F-Droid users can use other stores (like Aurora Store) to install the Kiwi browser.

**Comment by Tobi823** [comment]
> Fennec gets updates fairly now pls add

@bluecheeser where? can you send me a link and screenshot?

**Comment by bluecheeser** [comment]
![IMG_20210422_160336.jpg](https://user-images.githubusercontent.com/81776134/115700466-5448cd80-a384-11eb-8ae6-9a165d089ab2.jpg)
It's on fdroid

**Comment by Tobi823** [comment]
Now I understand you @bluecheeser. I though that by "Fennec" you meant the old "Firefox for Android" version from August 2020.
Some people (bot not me) still likes the old design.

Fennec was the first code name for "Firefox for Android".
> Firefox for mobile, codenamed "Fennec", was first released for Maemo in January 2010 with version 1.0
https://en.wikipedia.org/wiki/Firefox_for_Android#History

But in June 2019, Mozilla started to develop a new version with the code name "Fenix".
> On June 27, 2019, Mozilla unveiled Firefox Preview (codename "Fenix"), a redesigned version of Firefox for Android based on GeckoView
https://en.wikipedia.org/wiki/Firefox_for_Android#History

After August 2020, "Fenix" became "Firefox for Android".

> The Firefox for Android Beta channel was migrated to the Fenix branch in April 2020,[24] and it was officially released to the stable channel in August 2020 as version 79, branded as Firefox Daylight.[22][23] The last Fennec-based version was version 68, which was released in July 2019, and received bug and security fixes until July 2020.[25][26][27]
https://en.wikipedia.org/wiki/Firefox_for_Android#History

"Fennec F-Droid" (https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/) is based on the latest Firefox release. 

You can install "Firefox for Android" (which is "Fennec F-Droid" minus "proprietary bits" minus "telemetry") with FFUpdater.

**Comment by bluecheeser** [comment]
> You can install "Firefox for Android" (which is "Fennec F-Droid" + "proprietary bits" + "telemetry") with FFUpdater.
 
I don't want to use Firefox bc of its telemetry and trackers. Fennec should should be a good addition to FFupdater as it's more privacy friendly and has no tracking.

![IMG_20210423_172049.jpg](https://user-images.githubusercontent.com/81776134/115867110-4795a980-a458-11eb-9ffc-ed0c29b16a9e.jpg)

**Comment by Tobi823** [comment]
I think I am missing something.

Why don't you install "Fennec F-Droid" with the F-Droid app? F-Droid is equal or more secure that FFUpdater.

And there is a major problem:
The Github repository behind "Fennec F-Droid" (https://github.com/mozilla-mobile/fenix/releases) only offers the APK file with telemetry.
FFUpdater can only download and install the offered files from Github.

Even if I want to support "Fennec F-Droid" with FFUpdater, there is nothing I can do. You have to use F-Droid version.

**Comment by Coool** [comment]
Kiwi Browser has been updated recently to [137.0.7337.0](https://github.com/kiwibrowser/src.next/releases/tag/14310011181) version

Related:
- #621
- #468
- #121
- #36
- #35
- #22
