### ISSUE TITLE
cannot exclude brave

### ISSUE THREAD

**Issue by NANASHI0X74** [Tobi823/ffupdater#23]
Hi, I tried installing/updating brave via FFUpdater, but for some reason the download seems to be slow/fails every time, so I instead chose to install via aurora store, but FFUpdater is now bugging me with update notifications and I've noticed that even though there's an option to exclude apps from the automatic update check, it doesn't contain the brave browser

**Comment by Tobi823** [comment]
Upps.

I forgot to add "Brave" to the "Excluded applications" list.

And I realize that not every supported app (like Firefox Klar, Brave, Lockwise, ...) is installed with FFUpdater and not with Aurora.

I try to fix this bug as soon as possible.

**Comment by Tobi823** [comment]
FFUpdater 71.0.0 will fix the issue: You can disable Brave in Settings > Excluded applications

(But FFUpdater will not track which app is installed by FFUpdater itself or by an other App-Store because it's too complex. If you install Brave with Aurora, you have to disable Brave in Settings > Excluded applications)
