### ISSUE TITLE
Nightly URL doesn't redirect to the latest version

### ISSUE THREAD

**Issue by dannycolin** [Tobi823/ffupdater#3]
FFUpdater detects a new version (68.1a1) but the link that redirect to the latest version hasn't been updates on Mozilla server. It still redirects to 68.0a1.

68.0a1 https://download.mozilla.org/?product=fennec-nightly-latest&os=android&lang=multi
68.1a1 https://ftp.mozilla.org/pub/mobile/nightly/latest-mozilla-esr68-android-aarch64/

I've ping'ed the #mobile team but haven't received an response yet.

**Comment by Tobi823** [comment]
That's bad.

Maybe I have to ditch the api https://download.mozilla.org/?product=%s&os=%s&lang=multi at all (because it has no option for x86_64 or aarch64 devices - see https://ftp.mozilla.org/pub/mobile/releases/latest/README.txt and https://notabug.org/Tobiwan/ffupdater/issues/13).

I will investigate if HTML/FTP parsing (of the page https://ftp.mozilla.org/pub/mobile/nightly/) could solve our problems.

**Comment by dannycolin** [comment]
Here's a little heads up : 

I've filed a bugreport and got an response https://bugzilla.mozilla.org/show_bug.cgi?id=1565863
There's also a bugreport to find a solution to update FF w/o Play Store https://bugzilla.mozilla.org/show_bug.cgi?id=1192279

**Comment by dannycolin** [comment]
@Tobi823 the issue has been resolved upstream ;). See: https://bugzilla.mozilla.org/show_bug.cgi?id=1565863

Also, there's a bugreport to make sure that problem doesn't happen again in the future https://bugzilla.mozilla.org/show_bug.cgi?id=1566385

So, I'm closing this issue for now.

**Comment by Tobi823** [comment]
Thanks for your work

**Comment by dannycolin** [comment]
Just a quick heads up that [bug 1566385](https://bugzilla.mozilla.org/show_bug.cgi?id=1566385) has been resolved upstream.
