### ISSUE TITLE
Cannot find downloaded apk. It disappeared.

### ISSUE THREAD

**Issue by muchuelo** [Tobi823/ffupdater#33]
![FFUpdater](https://user-images.githubusercontent.com/76464195/111870175-68fc0500-8983-11eb-98e5-5b0cd8d7a5c5.png)

Using FFUpdater 72.0.0 on Android 7.1 (LineageOS 14.1, no Google)

Clicked on red arrow to download Firefox. Firefox downloaded successfully (data usage app showed ~67MB downloaded)
After download completed, nothing happened, so opened file explorer and searched for downloaded apk. Searched entire file system, including SD card, but could not find Firefox apk. (FFUpdater 'download' folder empty)

Downloaded apk apparently not saved (or deleted after download).
(An unfortunate waste of metered data).

Would be good to have an in-app setting for user to choose download location (including ability to select external SD card). Either that or an in-app button to "Open download folder".

This is my first time downloading an update in FFUpdater. I hope it is not intentionally deleting downloaded apk, especially when it apparently makes no attempt to install update after downloading!

**Comment by Tobi823** [comment]
I'll look into your bug later. 

FFUpdater should download the apk file to the folder Android > data > de.marmaro.krt.ffupdater > files > Download (e.g. /sdcard/Android/data/de.marmaro.krt.ffupdater/files/Download).

But FFUpdater will delete the files in this folder when you open FFUpdater after a long time or when you killed FFUpdater by swiping in the task overview.

**Comment by Tobi823** [comment]
In the next version (should be 72.1.0) FFUpdater will cache already downloaded apps.

> (FFUpdater 'download' folder empty)

Sorry, I did not read this

> Would be good to have an in-app setting for user to choose download location 

That's too much work and I don't see any advantage in this. File handling is a complex topic in Android and many Android versions behave differently.

The new "download cache" should be enough. If not, you can still go to the folder "/storage/emulated/0/Android/data/de.marmaro.krt.ffupdater/cache/Download"

> I hope it is not intentionally deleting downloaded apk, especially when it apparently makes no attempt to install update after downloading!

App installation is a complex topic, too. I think your download was deleted because the app should already be installed (but was not).
