### ISSUE TITLE
Firefox Nightly

### ISSUE THREAD

**Issue by RogerioTDS** [Tobi823/ffupdater#385]
No longer fetches updates for Firefox Nightly.
The last one available is March 19th.
![Screenshot_20230330-232309_FFUpdater](https://user-images.githubusercontent.com/120617835/229007052-93865279-0f77-4942-990d-476b8d0a18f5.png)

**Comment by RogerioTDS** [comment]
Actually, the installed version is from March 27th.
But it seems to me that he didn't get more updates afterwards, since the nightly updates are daily!
![Screenshot_20230331-152212_Firefox Nightly](https://user-images.githubusercontent.com/120617835/229214911-1eb24dd6-35ee-4134-b4d0-a963d347fa5e.png)

**Comment by Wojtaz0w** [comment]
Fix asap pls
![Screenshot_20230402-080918_FFUpdater.png](https://user-images.githubusercontent.com/104674625/229334947-79300ab1-7ec9-41b6-82d7-39de169e36e3.png)

**Comment by Tobi823** [comment]
@Wojtaz0w And please don't say "Fix asap pls" - that sounds rude. I don't think that was your intention, but other maintainer would block you because of it. There is no "asap" because this is my hobby project not my real work. I will fix it when I have the time. And "pls" is rude for me because I have the feeling that you haven't even taken the time to write out that word.

Keep in mind that people from other countries communicate differently. You can't expect that they simple understand what you want to say.

For example there are big differences between:

- communication: low-context (US, Germany, ...) and high-context (France, Japan) 
- feedback/evaluation: direct negative (Russia, Germany, France ...) and indirect negative (Mexico, Thailand) 
- and more: see https://www.businessinsider.com/the-culture-map-8-scales-for-work-2015-1?op=1

**Comment by Tobi823** [comment]
@RogerioTDS have overlooked your screenshot - I will the next days into it.

**Comment by Wojtaz0w** [comment]
My apologies. I never wanted to sound rude. By the way you're right. Its only wrong date - apk downloaded is fine. 
Before:
![Screenshot_20230402-160405_Firefox Nightly.png](https://user-images.githubusercontent.com/104674625/229358058-22304521-4ac3-4499-a960-451e757fb5ef.png)
After:
![Screenshot_20230402-160631_Firefox Nightly.png](https://user-images.githubusercontent.com/104674625/229358066-bd2ddc24-1bf3-4f20-af58-b8558fe3b627.png)

**Comment by Tobi823** [comment]
@WhiredPlanck Thanks for the info. I will try to fix this in the next days

**Comment by Wojtaz0w** [comment]
FYI Issue occurs since 77.7.12 (77.7.11 is fine)

**Comment by RogerioTDS** [comment]
Indeed, I went back to version 77.7.11 and there is no such problem!
![Screenshot_20230404-153220_FFUpdater](https://user-images.githubusercontent.com/120617835/229886086-b7732659-4873-40be-b80c-2f06a6be140e.png)

**Comment by ericJrdn** [comment]
Hi,
I'm using ffupdater 77.7.14. Have the same problem.
