### ISSUE TITLE
Adding tor browser & orbot to updater 

### ISSUE THREAD

**Issue by adnansumi98** [Tobi823/ffupdater#43]
Is there any possibility that tor browser & orbot will be added to the updater? I am suggesting this new feature in future updates.

**Comment by Tobi823** [comment]
I will not support Tor Browser and Orbot because it can be installed with F-Droid. Go to Settings > Repositories > Enable "Guardian Project Archive". Then refresh F-Droid by downswiping in Latest and search for "Tor Browser for Android"

I don't feel confident enough that I can install and update the Tor Browser or Orbot securely (because I think that there is much more at stake).
And Orbot is not a browser, it's a Tor proxy.
