### ISSUE TITLE
Option to add costum apps

### ISSUE THREAD

**Issue by ghost** [Tobi823/ffupdater#454]
This feature will be very useful so anyone can add the app they want without requesting everytime, I hope you'll consider my humble suggestion.

Thank you for your time.

**Comment by jfmcbrayer** [comment]
You should use the app "Obtainium" for this purpose.

**Comment by Tobi823** [comment]
@JohnBetaro Adding this feature is really difficult (because the user has to configure a lot of things e.g. which assets belongs to which ABI version etc.). I think it would be easier to help the developer of Obtainium instead of creating a custom solution.

https://github.com/ImranR98/Obtainium/issues/25
