### ISSUE TITLE
"No Network Connection" but updates anyway

### ISSUE THREAD

**Issue by TPS** [Tobi823/ffupdater#55]
@Tobi823 As shown below, many versions from v74.3.0 & before say "No Network Connection" on my Android 8.1.0 32-bit Moto G5+, but updates actually download & install when available.  On my Android 11 64-bit TCL 10L, everything shows & works as expected.  Fix available?

<Details>

![Screenshot_20210708-072430.png](https://user-images.githubusercontent.com/185902/125164399-04e29400-e160-11eb-8893-945ae9a926d7.png)

</Details>

**Comment by Tobi823** [comment]
I suspect that something on your smartphone is causing this problem because it works on my devices, I have not receive other bug reports and I changed the code for "internet detection" a "long" time ago (07.05.2021 with version 73.1.3).

I see that you are using a VPN. Can you try it without it?

I narrowed the bug down to this part:
```
private fun isInternetAvailableNewWay(cm: ConnectivityManager): Boolean {
    val activeNetwork = cm.activeNetwork ?: return false
    val capabilities = cm.getNetworkCapabilities(activeNetwork) ?: return false
    return capabilities.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET) &&
            capabilities.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)
}
```

This method evaluates to false/"no internet" if:
- ConnectivityManager.activeNetwork is null. According to the [documentation](https://developer.android.com/reference/android/net/ConnectivityManager#getActiveNetwork()) this can happen, if there is no default network.
- ConnectivityManager.getNetworkCapabilities is null. According to the [documentation](https://developer.android.com/reference/android/net/ConnectivityManager#getNetworkCapabilities(android.net.Network)) this can happen, if the network is unknown.
- the current network doesn't have the 
  - NET_CAPABILITY_INTERNET (`Indicates that this network should be able to reach the internet.`) or 
  - NET_CAPABILITY_VALIDATED (`Indicates that connectivity on this network was successfully validated. For example, for a network with NET_CAPABILITY_INTERNET, it means that Internet connectivity was successfully detected.`) capability.

Maybe you have disabled the internet detection on your smartphone (afaik Android phone are pinging Google server to detect, if they have access to the Internet)? Maybe something different?

**Comment by TPS** [comment]
You're right, of course, AFAICT.  I'll open this with them.  Thanks!
