### ISSUE TITLE
Thorium maintainer (Alex313031) drama

### ISSUE THREAD

**Issue by MinekPo1** [Tobi823/ffupdater#555]
If you are not aware, several users have raised that Alex313031 (which I will refer to as Alex from now on) including explicit images, either as easter eggs or by accident, in his repos.

One example is Thornium including `chrome://yiff`, which shows an explicit image, though the Android builds seem to not package the file correctly.

While Alex has been deleting some of the images, he and other contributors to Thorium have been closing, restricting and deleting issues related to these images, which, in my opinion, is not an appropriate response.

I'm creating this issue because, from what I've seen, many users may find this behaviour by Alex extremely out of place, thus it may be appropriate to add a disclaimer or remove the browser from ffupdaters listing (though I believe the latter is not quite justified), however I understand if the maintainers of ffupdater decide not to engage.

**Comment by MinekPo1** [comment]
See [Alex313031/Thorium#486](https://github.com/Alex313031/thorium/issues/468)

**Comment by zavocc** [comment]
The issue appears to be removed. I think putting a warning about this in its install page would be a good idea?

**Comment by MinekPo1** [comment]
> The issue appears to be removed. I think putting a warning about this in its install page would be a good idea? 

that was about what I feel is best I think? people have said they lost trust for thorium after this...

**Comment by Tobi823** [comment]
Sorry for my late reply.

In my opinion including these images into Thorium was unprofessional. But I think he learned his lesson and he will never do it again.

I don't want to judge him too much, because he has invested a lot of free time in his passion project and it's very easy to make mistakes.

**Comment by Tobi823** [comment]
I almost made a critical mistake too. For a moment I thought that I had added a browser to FFUpdater that was spying on users. And I blamed myself for not testing the browser better.

(But it was a false alarm. The Kiwi browser needs to route Bing searches through its own servers so the developer receives money from Microsoft)

**Comment by Tobi823** [comment]
> As much as I wanted to like Thorium, just look at all the projects he has going on, the work involved just to keep up with one version and the recent long hiatus with 0 commits...on top of keeping up with real life.
Just makes it all that much more unfortunate given that I can absolutely get behind what he wants to achieve with keeping stuff working on legacy devices and software.

It seems that the hiatus is over. But this is the risk with every browser - you don't have any guarantees. That's why I added the age information into the UI. (At least you can see if the latest version of an app is really old)
