### ISSUE TITLE
Add support for resuming

### ISSUE THREAD

**Issue by Sepero** [Tobi823/ffupdater#56]
Ability switch between networks and resume downloads. Periodically check if the download was interrupted, and resume.

**Comment by Tobi823** [comment]
I'm using the android.app.DownloadManager (https://developer.android.com/reference/android/app/DownloadManager) for downloading.
This interface only allows the enqueuing / cancellation of downloads. There is no way to pause/resume downloads manually.
But downloads should automatically be resumed:
> The download manager will conduct the download in the background, taking care of HTTP interactions and retrying downloads after failures or across connectivity changes and system reboots. 

On my Android emulator, the download is resumed most of the time when I 
 - enable and disable the airplane mode
 - disable WiFi and fallback to mobile internet.

I don't know why your downloads or the downloads on my emulator don't always resumed. I guess resuming it's a complex process.

I'm afraid there's nothing I can do. I have to use the android.app.DownloadManager because it is well supported by all Android smartphones, well integrated into the operating system, doesn't required additional dependencies and this "fail to resume download" error occurs only rarely.

**Comment by Sepero** [comment]
Resuming a download is a very simple process, but most generic downloaders are just sloppy. If it's worth your trouble, you could include a small `curl` binary to download the files instead. If it's too much work, then don't bother with it. It's not a big deal. I appreciate you putting the links.

When I was having network issues, I copied the links from FFUpdater, and pasted them into a real downloader. Then the downloads completed, and I just installed from the apks
