### ISSUE TITLE
Firefox Preview : impossible to retrieve url from Github error

### ISSUE THREAD

**Issue by yhoyhoj** [Tobi823/ffupdater#6]
Hi, thanks for the new version ! Great improvement in quality and usefulness ! The download works for "classic" Firefox .

Unfortunately, the app fails to retrieve the download link for Firefox Preview.
Instead there are 2 error messages :
"Impossible to retrieve the url from Github" (translation to English from another language)
"Installation of the app has not succeeded. You can close this screen." (translation to English from anther language)

Same result for Firefox Preview 4.5.0 a few days ago and 5.0.0 now.

Version of the app: 68.0 (f-droid)
Android version: 9 (LineageOS 16.0)

**Comment by Tobi823** [comment]
Can you uninstall and reinstall the app? I know it sounds crazy but it worked on my smartphone.

I think this bug is caused by the new app trying to read the old settings. Because debugging this strange error is more difficult, I planned to do it but I forgot it 🙈

Other possibility: You are temporary blocked by Github for an hour. Can you visit https://api.github.com/rate_limit and check this?
![2020-05-13 21_35_30-Mozilla Firefox](https://user-images.githubusercontent.com/10066140/81856920-c6544800-9561-11ea-95bf-75c32bc647d8.png)

**Comment by Tobi823** [comment]
Nevermind - this is a different bug.

The app searches in https://api.github.com/repos/mozilla-mobile/fenix/releases/latest for assets containing "aarch64" in there name. 

But the name of the asset (e.g. "firefox_preview_v5.0_arm64.apk") for modern 64bit ARM CPUs contains "arm64" and not "aarch64".

That's the problem when testing with x86_64 android emulators only 😬

I will add some tests and release a new version
