### ISSUE TITLE
Timely updates

### ISSUE THREAD

**Issue by hank-tu-biz** [Tobi823/ffupdater#628]
Brave browser v. ending 165 is available on PlayStore now but not through ffupdater. Shouldn't this be impossible? If so, plz fix. If not, plz advise.

**Comment by Tobi823** [comment]
Hi,

FFUpdater uses GitHub for searching and downloading Brave Browser updates. 

On GitHub, there is no  v1.69.165. only  v1.69.168 (flagged as pre-release) +  v1.69.167 (flagged as pre-release) and v1.69.162 (normal release) are available.
That's why you can only install 1.69.162 with FFUpdater. 

But I am confident, that the developers will fix their GitHub page by either unflagging a newer release or creating a new normal release.

**Comment by hank-tu-biz** [comment]
Thank you. Very much appreciated.

Sep 11, 2024 09:56:25 Tobias Hellmann ***@***.***>:
