### ISSUE TITLE
google play  installs firefox after ffupdater installed firefox.

### ISSUE THREAD

**Issue by yutayu** [Tobi823/ffupdater#638]
I want to use ffupdater for updating firefox.
But google play installs firefox  upon firefox installed by ffupdater.

**Comment by Tobi823** [comment]
Bad news - to my knowledge there is no fix for this on Android 13 or lower. 

On Android 14, FFUpdater makes sure that only FFUpdater can update Firefox (with the setRequestUpdateOwnership feature)

**Comment by yutayu** [comment]
Thanks.

**Comment by LukasThyWalls** [comment]
Hello.

Only to add that the reason (at least in my case for this) is because, for some reason, the build number in Google Play is higher than the one in the official Firefox website for the same version.

For example, with Firefox 135.0.1:
* The version installed by FFupdater, downloaded directly from the Firefox website have the build number 2016074234
![Image](https://github.com/user-attachments/assets/11a873a1-e3bf-46d2-8e32-0c096d25ea30) 
* In Google Play, the build number is 2016074239 (Screenshot from Aurora Store App)
![Image](https://github.com/user-attachments/assets/789eff66-940d-4b8d-a812-9c414c5612eb)

I don't know exactly why It is like that.

Also, maybe both apps apks are using the same sign, but also I had lately a lot of issues with Google Play showing, trying (and failing) updates for apps that are installed with other app stores (F-Droid), and I though at first that my problem was that, but I see It's a little more complicated.

Anyway, thanks!

**Comment by LukasThyWalls** [comment]
Hello.

Only to update that [I notified the issue in their bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1958579), and this was [their response:](https://bugzilla.mozilla.org/show_bug.cgi?id=1958579#c3)

> We've had intermittent issues (for months) with Play Store submissions taking an inordinate amount of time to be reviewed before publishing. This is out of our control and it leads to cases you are seeing where the versions don't match for hours to sometimes days.
> 
> Since we can't do anything about this, I'm closing this as won't fix until we have some new information that leads us to believe this is a separate issue from the one I've described.

¯\\_ (ツ)_/¯
