### ISSUE TITLE
ffupdater apk without fdroid?

### ISSUE THREAD

**Issue by DevJackSmith** [Tobi823/ffupdater#65]
Hello, thanks for great app. Any chance there's a way to download and install ffupdater apk directly from github/gitlab/etc? (I don't want to wait days for fdroid to release a fix every time)

**Comment by DevJackSmith** [comment]
Maybe I can help make a github action workflow if you tell me how you build it? It's free up to 2000 minutes a month I believe

**Comment by Tobi823** [comment]
> (I don't want to wait days for fdroid to release a fix every time)

I don't wont it either. The folks from F-Droid do a great job and the wait time is ok for a feature upgrade. But it's to slow for emergency releases.

> Maybe I can help make a github action workflow if you tell me how you build it?

I'm already using GitHub Actions for my daily unit tests. But building/releasing an APK file seems complicated - andd Android Studio has a nice way to generate a signed APK file. 

I will add this "build signed APK file + upload signed APK file to GitHub and GitLab" step to my "release new version" checklist (checklists are ideal for not forgetting important stuff).
Releasing a signed APK is in my opinion better than releasing an unsigned APK because an attacker have to retrieve the key from my computer before he can distribute malware over GitHub/GitLab.

GitHub and GitLab allow me to add an APK file to an existing release.
Notabug.org only allows me to create a new release with an APK file.
Releasing my self build FFUpdater version on GitHub and GitLab should be enough.

More info: https://github.com/Tobi823/ffupdater#temporary-builds

**Comment by DevJackSmith** [comment]
Thank you that's great. If you are bored and want suggestions on the next step, I would think a background service that checks for new released version on GitHub would be helpful too. Anyway, thanks for this. Keep up the great job :)

**Comment by Tobi823** [comment]
Thanks :)

> I would think a background service that checks for new released version of ffupdater on GitHub would be helpful too.

I will think about it. But the problem is, that you can't install FFUpdater from GitHub if you have FFUpdater from F-Droid installed. Both APKs are signed with different keys and Android only allows an app update with the same key.

The user has to first uninstall FFUpdater from F-Droid before he can install FFUpdater from GitHub.

The only possibility is that the user is only informed about an update + maybe automatic download to the "Downloads" folder

**Comment by DevJackSmith** [comment]
Giving people a choice of fdroid or GitHub source seems ok l. Other apps do it too.
Notification of new release and maybe download or link to download is great. Fair email app for example does it.

**Comment by TPS** [comment]
@Tobi823 I hope you could revisit this issue.  Since FFUpdater's entire purpose is to update apps anyway, it'd be convenient to update itself on whatever schedule that it does the others.  As for the different builds, wouldn't slightly different flavors for Gradle allow to change which source is used to update itself?

**Comment by Tobi823** [comment]
Apparently there are more people who want to use FFUpdater without F-Droid than I thought. I will implement it (updating FFUpdater with the releases from my GitHub repository) next month.

**Comment by TPS** [comment]
@Tobi823 I look forward to this update.  Could it be possible to update from wherever this is installed from?  I tend to use the GitHub `apk` release than F-Droid's, as I don't wish to wait 'til whenever it's released there, & 1 can't update the other.

**Comment by Tobi823** [comment]
> @Tobi823 I look forward to this update. Could it be possible to update from wherever this is installed from? I tend to use the GitHub `apk` release than F-Droid's, as I don't wish to wait 'til whenever it's released there, & 1 can't update the other.

Nope, you have to uninstall the F-Droid version and then install the version from GitHub.

The reason: FFUpdater from GitHub/GitLab/my personal repository is signed by my private key. But FFUpdater is signed by the F-Droid key. Android requires than an update is signed by the same key.

**Comment by TPS** [comment]
@Tobi823 No, I understood that.  I mean, whenever this internal update is implemented, could it automatically choose either GitHub release or F-droid's, based on where current install is from?  Failing that, could we have a settings option to do that?

**Comment by Tobi823** [comment]
The self-update is only possible if you install FFUpdater from GitHub/GitLab/my personal repository. Updates will be downloaded from my GitHub-Repository. It will look like this:

![screenshot](https://user-images.githubusercontent.com/10066140/162577236-f727e796-7ec0-4de0-b088-7a2055ab5579.png)


The self-update is not possible, if you install FFUpdater from the website https://f-droid.org/en/packages/de.marmaro.krt.ffupdater/.
Is there really a need for it? I can't imagine why people would want to download FFUpdater from the F-Droid website and not use the F-Droid app.

**Comment by TPS** [comment]
I lean more to your thinking if the update will be GitHub-release based.  But I think most users are via F-Droid, & so might complain when the update that shows in-app (several days before F-Droid's) won't "take."

**Comment by Tobi823** [comment]
> But I think most users are via F-Droid, & so might complain when the update that shows in-app (several days before F-Droid's) won't "take."

For F-Droid user, it will look like this:

![screenshot](https://user-images.githubusercontent.com/10066140/162640291-d90d677c-5bdc-4bdf-a295-d0e0a2bd9f1f.png)

When you install FFUpdater from F-Droid, you will not see the FFUpdater entry in the FFUpdater app. So there is no way that a F-Droid user can click on the "download arrow button" and get an error (that the GitHub-version can't update the F-Droid-version)

**Comment by Tobi823** [comment]
The reason why I don't want to implement the self-update for the F-Droid version for now: Other features like automatic background update, Brave Beta/Nightly etc. have a higher usefulness and are also wanted by more people.

**Comment by TPS** [comment]
It looks good.  I'll wait for next update to know more.  Thanks! 🙇🏾‍♂️

**Comment by TPS** [comment]
I can report that FFU updated itself to this last version perfectly, so this can be closed ftw.  Thanks, @Tobi823. 🙇🏾‍♂️

**Comment by Tobi823** [comment]
Thanks :)
