### ISSUE TITLE
Excluded application doesn't stop it from notifying me about updates for Firefox Nightly

### ISSUE THREAD

**Issue by jackleson** [Tobi823/ffupdater#97]
I installed Firefox Nightly. it then told me there was an update available via notification a few times over a few days and then I added Firefox Nightly to Excluded applications. I expect it would stop checking for updates and telling me about them, but even after updating Firefox Nightly once (I assume since it had already checked for updates it was still telling me about old updates even though it might not have been checking anymore) it still kept checking for updates and telling me about them.

**Comment by Tobi823** [comment]
Sorry for the late reply, I've been busy with University lately.

**Comment by Tobi823** [comment]
> it still kept checking for updates and telling me about them

I found the bug in FFUpdater. The "Firefox Release", "Firefox Beta" and "Firefox Nightly" could not be excluded from background update checks because internally I used their old names (FENIX_RELEASE, FENIX_BETA, FENIX_NIGHTLY). 

But in the next version you can simply exclude Firefox Nightly from the background update check.

**Comment by Tobi823** [comment]
Version 75.0.0 with a fix for this bug is now released.
